spring:
  application:
    name: ORDER-SERVICE
  config:
    import: optional:configserver:${CONFIG_SERVER:http://localhost}:8888}
  kafka:
    bootstrap-servers: ${BOOTSTRAP_SERVER:localhost:29092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.JsonSerializer

server:
  port: ${PORT:8081}

eureka:
  instance:
    client:
      serverUrl:
        defaultZone: ${SERVICE_REGISTRY:http://localhost/8761/eureka/}

kafka:
  topic:
    name: ${TOPIC_NAME:current-topic}